/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/[type]/detail/[id]': RouteRecordInfo<'/[type]/detail/[id]', '/:type/detail/:id', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/develop/document': RouteRecordInfo<'/develop/document', '/develop/document', Record<never, never>, Record<never, never>>,
    '/help/': RouteRecordInfo<'/help/', '/help', Record<never, never>, Record<never, never>>,
    '/support/chain': RouteRecordInfo<'/support/chain', '/support/chain', Record<never, never>, Record<never, never>>,
  }
}
