/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/DeveDetail': RouteRecordInfo<'/DeveDetail', '/DeveDetail', Record<never, never>, Record<never, never>>,
    '/DevelopDocument': RouteRecordInfo<'/DevelopDocument', '/DevelopDocument', Record<never, never>, Record<never, never>>,
    '/HelpCenter': RouteRecordInfo<'/HelpCenter', '/HelpCenter', Record<never, never>, Record<never, never>>,
    '/SupportingChain': RouteRecordInfo<'/SupportingChain', '/SupportingChain', Record<never, never>, Record<never, never>>,
  }
}
